### ISSUE TITLE
add {opusreader2} to the list?

### ISSUE THREAD

**Issue by philipp-baumann** [bryanhanson/FOSS4Spectroscopy#10]
Hi @bryanhanson @ThomasKnecht and me have been working on a new implementation of a Bruker OPUS reader in R. 

https://github.com/spectral-cockpit/opusreader2

We managed to reverse engineer many parts already, part is shared with py brukeropusreader but there is new entries; although we are not yet v1 the interface is stable. We are a bit behind with the CRAN release that we plan. There is a vignette that I need to write up and I wanted to give some more insights on the parsing routine/algorithm, i.e. the file structure and encoding of Bruker OPUS binary files.

If you need more info or a short text, please let me know. 

Thank you and cheers,
Philipp

**Comment by bryanhanson** [comment]
Definitely adding this to the list.  May be a day or two before I can re-run the whole thing however.  Will let you know.

Thanks for the suggestion!

**Comment by philipp-baumann** [comment]
> Definitely adding this to the list. May be a day or two before I can re-run the whole thing however. Will let you know.
> 
> Thanks for the suggestion!

Cool, thank's a lot!

**Comment by bryanhanson** [comment]
Done... thanks again!
