### ISSUE TITLE
Other software and initiative

### ISSUE THREAD

**Issue by zecojls** [bryanhanson/FOSS4Spectroscopy#11]
Hi,

This is such a great effort. I opened this issue because not only I would like to suggest a few packages, but also present our initiative called [Soil Spectroscopy for Global Good](https://soilspectroscopy.org/). In this initiative, we have been engaging with the soil spectroscopy community for developing open solutions, have developed a ring trial experiment (which has a paper submitted on it), and also compiled the [Open Soil Spectral Library](https://soilspectroscopy.github.io/ossl-manual/), which includes an open database and derived solutions, like the [OSSL Explorer](https://explorer.soilspectroscopy.org/) and the [OSSL Engine](https://engine.soilspectroscopy.org/).  It is really awesome to find your work because this indicates that there are great people working on similar issues that prevent a more universal use of spectroscopy. If you are interested in joining our network and receiving more information, please fill out [this form](https://forms.gle/r1Uw8mGjpJiFyey97).

In addition, these are some packages that I came across or that routinely use that could be added to your listing:

Name: pycaltransfer
Description: Calibration transfer for chemometrics and spectral data applications.
Lang: Python
Focus: any
URL: https://pypi.org/project/pycaltransfer/
Paper: https://doi.org/10.1016/j.aca.2022.340154

On [this page](https://soilspectroscopy.github.io/ossl-manual/soil-spectroscopy-tools-and-users.html#soil-spectroscopy-software), we also listed some R software that we have been employing in our projects.

Cheers

**Comment by bryanhanson** [comment]
Nice stuff!  I'm adding pycaltransfer to FOSS4Spectroscopy.  Looks like this package would apply in principle to any kind of spectroscopy?  I'm wondering what to put for the "focus" field. Can you look at the existing entries and suggest something?

Thanks for contributing!

**Comment by zecojls** [comment]
Thanks. Do you want me to make a PR?

It seems that pycaltransfer is focused on UV-Vis and NIR.

**Comment by bryanhanson** [comment]
No PR needed, I'll just update the focus field with UV-Vis and NIR.  Thanks.

**Comment by bryanhanson** [comment]
Done!  Thanks again.
