### ISSUE TITLE
fix opusreader2 link

### ISSUE THREAD

**Issue by philipp-baumann** [bryanhanson/FOSS4Spectroscopy#12]
>  Done... thanks again!

_Originally posted by @bryanhanson in https://github.com/bryanhanson/FOSS4Spectroscopy/issues/10#issuecomment-1683060849_

=> thanks for the record. I just noticed that the URL is broken:
should be https://spectral-cockpit.github.io/opusreader2/index.html
but it is https://spectral-cockpit.github.io/opusreader2/A289

is the FOSS4Spectroscopy.Rmd still up to date? I can also make a PR rendering it, if so.

**Comment by bryanhanson** [comment]
Wonder how that happened.  I'll fix it right now.  Thanks!
