### ISSUE TITLE
Addition of simplerspec R package

### ISSUE THREAD

**Issue by philipp-baumann** [bryanhanson/FOSS4Spectroscopy#2]
Hi Bryan,
thanks for the nice collection. I have been undertaking some steps to streamline spectral processing and modeling, the package is here:
https://github.com/philipp-baumann/simplerspec
Here a short tour d'horizon:
https://github.com/philipp-baumann/simplerspec-pedometron-article
If you feel like this is useful, you could add it on your list.
Cheers,
Philipp

**Comment by bryanhanson** [comment]
Super Philipp, I will add this in the very near future.  I'm currently refining the automatic checking of commit and issue dates, which is a little out of my skill set and so will take a bit more time.  But I'm learning!

May I ask, how did you come across FOSS4Spectroscopy?  You are the first to add something!

**Comment by bryanhanson** [comment]
I added `simplerspec`, but, I need to add some details: Looks like it is geared toward mid-IR data sets, can it work with other types of spectroscopies?

**Comment by philipp-baumann** [comment]
Hi Bryan,
sorry for the late reply, was a bit busy these days. Great, thanks! It is mostly targeted towards IR spectroscopy, both mid-IR and NIR. The data structure is a bit opinionated (using tibble data frames and appending spectral data as list-columns instead of entire matrices), but it can handle both IR ranges. In case of NIR, the X-unit is wavenlength (values are in a separate column called "wavelengths" for raw spectra), and for mid-IR it is wavenumber ("wavenumbers" column). An example of the ASD wrapper for reading spectra is (`read_asd_bin`, see https://github.com/philipp-baumann/simplerspec/blob/master/R/read-asd.R).

Hope this clarifies. Let me know if you need more infos.

Best, Philipp

**Comment by bryanhanson** [comment]
OK thanks will update the database, close this issue.
