### ISSUE TITLE
Suggestion: "The ‘plantspec’ r package: A tool for spectral analysis of plant stoichiometry"

### ISSUE THREAD

**Issue by philipp-baumann** [bryanhanson/FOSS4Spectroscopy#3]
Dear Bryan,

I'm actively following your your comprehensive and frequently updated collection of FOSS spectroscopy software. Thanks a lot for your efforts, I find it a very nice page! I'm convinced this is very beneficial for many science communities and folks caring about plenty of fascinating real-world applications of spectral estimation. 

I recently stumbled upon this:
Griffith, D. M., & Anderson, T. M. (2019). The ‘plantspec’ r package: A tool for spectral analysis of plant stoichiometry. Methods in Ecology and Evolution, 10(5), 673–679. https://doi.org/10.1111/2041-210X.13143

https://github.com/griffithdan/plantspec

Best,
Philipp

**Comment by bryanhanson** [comment]
Thanks Philipp for your kind words and interest, and the suggestion.  I had looked at `plantspec` once before, and decided it was too narrow.  But a second look suggests its worthy so I'll add it in the next day or two.  I appreciate it!

**Comment by bryanhanson** [comment]
Added in https://github.com/bryanhanson/FOSS4Spectroscopy/commit/bb1e1c4e31acf8e37cc56e76d801ff6830ebb4d1 Page should update within a few minutes.  Thanks again!

**Comment by philipp-baumann** [comment]
Hi Bryan, thank you!
