### ISSUE TITLE
add NmrLineGuru to the list

### ISSUE THREAD

**Issue by stonefonly** [bryanhanson/FOSS4Spectroscopy#4]
Hi: could you add NmrLineGuru to the list? See this repo. Thanks.
https://github.com/stonefonly/NmrLineGuru

**Comment by erwanp** [comment]
Hello @stonefonly . NmrLineGuru looks like a nice package, but is it open-source? The GitHub repo only shows screenshots and points toward an already compiled version.

**Comment by bryanhanson** [comment]
Really nice web site and tutorials!

Unfortunately, MATLAB packages are not included in our list as MATLAB is neither free nor open source.  Some developers do make their own MATLAB code open source, but the MATLAB itself is not.
