### ISSUE TITLE
add SpectroChempy ?

### ISSUE THREAD

**Issue by atravert** [bryanhanson/FOSS4Spectroscopy#6]
Dear Bryan:

Thank you very much for this VERY USEFUL work for the community

I believe that SpectroChemPy fulfills the criteria to be included in the list:  
repo: https://github.com/spectrochempy/spectrochempy  
documentation and examples: www.spectrochempy.fr  

Best regards
Arnaud.

**Comment by bryanhanson** [comment]
Arnaud, thanks for sharing this, it's totally appropriate and I will add it in the very near future.

**Comment by bryanhanson** [comment]
Arnaud, thanks again, added via https://github.com/bryanhanson/FOSS4Spectroscopy/commit/47959debe57cd33fab9b07fb13ee84e3c2c6f6a5
