### ISSUE TITLE
Consider adding uvvistauc R package

### ISSUE THREAD

**Issue by solarchemist** [bryanhanson/FOSS4Spectroscopy#7]
https://github.com/solarchemist/uvvistauc

The package comes with an example dataset and [a vignette](https://htmlpreview.github.io/?https://github.com/solarchemist/uvvistauc/blob/master/doc/intro.html). It has a narrow focus on Tauc plots, and it uses semi-automatic algorithm to determine the optical band gap (the function requires some user input). 
I am aware there are multiple prior published papers on completely automatic Tauc algorithms (see the notes the package vignette), but I have not found their actual code. I'm not aware of any prior R packages for either automatic or semi-automatic Tauc plots.

An earlier version of my code (before I rewrote it as a package) formed a major part of the data analysis in a scientific paper I co-authored. (That is to say, I feel confident that my approach is not completely awful).

I would love to hear critique or comments, and if you feel this package is up to the standards of your collection I'd be thrilled.

**Comment by bryanhanson** [comment]
Taha, this package looks great and I will add it to the site w/i a week or two (I'm concentrating on finishing up a project right now).  Thanks for the submission.

**Comment by bryanhanson** [comment]
So sorry for the delay!  It's in there now.
