### ISSUE TITLE
rchemo and Jchemo

### ISSUE THREAD

**Issue by mlesnoff** [bryanhanson/FOSS4Spectroscopy#9]
you may be interested by the two following stable packages (R and Julia):
https://github.com/mlesnoff/rchemo
https://github.com/mlesnoff/Jchemo.jl
"Dimension reduction, Regression and Discrimination for Chemometrics"
with many utilities

**Comment by bryanhanson** [comment]
Thanks Matthieu, I’ll put these into the database no later than next week!  Bryan

**Comment by mlesnoff** [comment]
Thanks Bryan

**Comment by bryanhanson** [comment]
Updated via https://github.com/bryanhanson/FOSS4Spectroscopy/commit/cdc278322e79a2f6870832383e88e2038c5c04eb

It might be good to put a "spectroscopy" tag on these repos so those so-inclined will find your stuff more readily.

Thanks for the submission, you are doing nice work.
